Repository ClearGDPR/ClearGDPR, pull requests merged in 2018-07, with the labels that each got.

#232 Requiring handlers in props
  admin/src/components/Users/DeleteUser.js
  admin/src/components/Users/Users.js
  admin/src/components/core/cards/dashboard/Card.js
  admin/src/components/core/cards/dashboard/Sidenav.js
Labels: frontend

#274 Renamed subject data status to keep consistency
  frontend/src/elements/components/UserData.js
Labels: frontend

#273 Added users prop-types
  admin/src/components/Users/Users.js
  admin/src/containers/Rectifications/Rectifications.js
  admin/src/containers/Users/Users.js
Labels: frontend

#275 Yarn lock wasn't up to date (likely merge issues)
  admin/yarn.lock
Labels: frontend

#289 Updated GraphCard proptypes to avoid build failing
  admin/src/components/core/cards/dashboard/GraphCard.js
Labels: bug, frontend

#305 Added missing prop type
  admin/src/components/core/cards/dashboard/ItemsCard.js
Labels: bug, frontend

#315 Added timezone, so date formatting in tests is consistent
  admin/package.json
Labels: devops, frontend

#317 Set version to 1.0.0 so we can rely on tags for releases
  admin/package.json
  api/package.json
  cg/package.json
  frontend/package.json
  package.json
  website/package-lock.json
  website/package.json
Labels: devops

#336 Fixed deleting a processor in the UI
  admin/src/containers/Processors/ProcessorsContext.js
Labels: bug, frontend

#341 Feature/buttons styles extended
  admin/src/components/MainLayout/styles.css
  admin/src/components/core/Common/Buttons/Buttons.js
  admin/src/components/core/Common/Buttons/buttons.css
  admin/src/components/core/cards/dashboard/Elements.js
  admin/src/components/core/cards/dashboard/Sidenav.js
  admin/src/components/core/pages/Dashboard.js
  admin/src/routes.js
  admin/src/theme/main.css
Labels: UX/UI

#352 Hide 'sign in' and 'sign up' links from registered users
  frontend/src/containers/App.js
Labels: demo, frontend

#353 Fix some things that causes difficulties during setup process
  admin/README.md
  api/scripts/generate-config.js
Labels: frontend

#354 Sign up form - show error received from backend call
  frontend/src/containers/SignUp.js
Labels: demo, frontend

#357 Complete right to objection
  cg/migrations/20180725221648_add_objection_to_subjects_table.js
  cg/scripts/blockchain-function-test.js
  cg/scripts/deploy-blockchain-contract.js
  cg/smart_contracts/ClearGDPR.sol
  cg/src/domains/processors/processors.controller.js
  cg/src/domains/processors/processors.listeners.js
  cg/src/domains/processors/processors.routes.js
  cg/src/domains/processors/subjects.service.js
  cg/src/domains/subjects/subjects.controller.js
  cg/src/domains/subjects/subjects.routes.js
  cg/src/domains/subjects/subjects.service.js
  cg/src/domains/subjects/subjects.validators.js
  cg/src/utils/blockchain.js
  cg/src/utils/blockchain/contract-abi.json
  cg/src/utils/blockchain/contract-bytecode.js
  cg/test/management/subjects.api.spec.js
  cg/test/processors/processors.api.spec.js
  cg/test/processors/processors.listeners.spec.js
  cg/test/subjects/__snapshots__/subjects.api.spec.js.snap
  cg/test/subjects/subjects.api.spec.js
Labels: api, smart-contract
